/*
 * CUDAWrapper - Java bindings for NVIDIA CUDA driver and runtime API
 *
 * Copyright (c) 2009-2016 Marco Hutter - http://www.CUDAWrapper.org
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CUDAWrapper_runtime_CUDAWrapper */

#ifndef _Included_CUDAWrapper_runtime_CUDAWrapper
#define _Included_CUDAWrapper_runtime_CUDAWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef CUDAWrapper_runtime_CUDAWrapper_CUDART_VERSION
#define CUDAWrapper_runtime_CUDAWrapper_CUDART_VERSION 8000L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaHostAllocDefault
#define CUDAWrapper_runtime_CUDAWrapper_cudaHostAllocDefault 0L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaHostAllocPortable
#define CUDAWrapper_runtime_CUDAWrapper_cudaHostAllocPortable 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaHostAllocMapped
#define CUDAWrapper_runtime_CUDAWrapper_cudaHostAllocMapped 2L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaHostAllocWriteCombined
#define CUDAWrapper_runtime_CUDAWrapper_cudaHostAllocWriteCombined 4L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaHostRegisterDefault
#define CUDAWrapper_runtime_CUDAWrapper_cudaHostRegisterDefault 0L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaHostRegisterPortable
#define CUDAWrapper_runtime_CUDAWrapper_cudaHostRegisterPortable 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaHostRegisterMapped
#define CUDAWrapper_runtime_CUDAWrapper_cudaHostRegisterMapped 2L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaHostRegisterIoMemory
#define CUDAWrapper_runtime_CUDAWrapper_cudaHostRegisterIoMemory 4L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaPeerAccessDefault
#define CUDAWrapper_runtime_CUDAWrapper_cudaPeerAccessDefault 0L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaStreamDefault
#define CUDAWrapper_runtime_CUDAWrapper_cudaStreamDefault 0L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaStreamNonBlocking
#define CUDAWrapper_runtime_CUDAWrapper_cudaStreamNonBlocking 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaEventDefault
#define CUDAWrapper_runtime_CUDAWrapper_cudaEventDefault 0L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaEventBlockingSync
#define CUDAWrapper_runtime_CUDAWrapper_cudaEventBlockingSync 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaEventDisableTiming
#define CUDAWrapper_runtime_CUDAWrapper_cudaEventDisableTiming 2L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaEventInterprocess
#define CUDAWrapper_runtime_CUDAWrapper_cudaEventInterprocess 4L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleAuto
#define CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleAuto 0L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleSpin
#define CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleSpin 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleYield
#define CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleYield 2L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleBlockingSync
#define CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleBlockingSync 4L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaDeviceBlockingSync
#define CUDAWrapper_runtime_CUDAWrapper_cudaDeviceBlockingSync 4L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleMask
#define CUDAWrapper_runtime_CUDAWrapper_cudaDeviceScheduleMask 7L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaDeviceMapHost
#define CUDAWrapper_runtime_CUDAWrapper_cudaDeviceMapHost 8L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaDeviceLmemResizeToMax
#define CUDAWrapper_runtime_CUDAWrapper_cudaDeviceLmemResizeToMax 16L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaDeviceMask
#define CUDAWrapper_runtime_CUDAWrapper_cudaDeviceMask 31L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaArrayDefault
#define CUDAWrapper_runtime_CUDAWrapper_cudaArrayDefault 0L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaArrayLayered
#define CUDAWrapper_runtime_CUDAWrapper_cudaArrayLayered 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaArraySurfaceLoadStore
#define CUDAWrapper_runtime_CUDAWrapper_cudaArraySurfaceLoadStore 2L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaArrayCubemap
#define CUDAWrapper_runtime_CUDAWrapper_cudaArrayCubemap 4L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaArrayTextureGather
#define CUDAWrapper_runtime_CUDAWrapper_cudaArrayTextureGather 8L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaIpcMemLazyEnablePeerAccess
#define CUDAWrapper_runtime_CUDAWrapper_cudaIpcMemLazyEnablePeerAccess 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaStreamCallbackNonblocking
#define CUDAWrapper_runtime_CUDAWrapper_cudaStreamCallbackNonblocking 0L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaStreamCallbackBlocking
#define CUDAWrapper_runtime_CUDAWrapper_cudaStreamCallbackBlocking 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType1D
#define CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType1D 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType2D
#define CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType2D 2L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType3D
#define CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType3D 3L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceTypeCubemap
#define CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceTypeCubemap 12L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType1DLayered
#define CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType1DLayered 241L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType2DLayered
#define CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceType2DLayered 242L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceTypeCubemapLayered
#define CUDAWrapper_runtime_CUDAWrapper_cudaSurfaceTypeCubemapLayered 252L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaTextureType1D
#define CUDAWrapper_runtime_CUDAWrapper_cudaTextureType1D 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaTextureType2D
#define CUDAWrapper_runtime_CUDAWrapper_cudaTextureType2D 2L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaTextureType3D
#define CUDAWrapper_runtime_CUDAWrapper_cudaTextureType3D 3L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaTextureTypeCubemap
#define CUDAWrapper_runtime_CUDAWrapper_cudaTextureTypeCubemap 12L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaTextureType1DLayered
#define CUDAWrapper_runtime_CUDAWrapper_cudaTextureType1DLayered 241L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaTextureType2DLayered
#define CUDAWrapper_runtime_CUDAWrapper_cudaTextureType2DLayered 242L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaTextureTypeCubemapLayered
#define CUDAWrapper_runtime_CUDAWrapper_cudaTextureTypeCubemapLayered 252L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaMemAttachGlobal
#define CUDAWrapper_runtime_CUDAWrapper_cudaMemAttachGlobal 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaMemAttachHost
#define CUDAWrapper_runtime_CUDAWrapper_cudaMemAttachHost 2L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaMemAttachSingle
#define CUDAWrapper_runtime_CUDAWrapper_cudaMemAttachSingle 4L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaOccupancyDefault
#define CUDAWrapper_runtime_CUDAWrapper_cudaOccupancyDefault 0L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaOccupancyDisableCachingOverride
#define CUDAWrapper_runtime_CUDAWrapper_cudaOccupancyDisableCachingOverride 1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaCpuDeviceId
#define CUDAWrapper_runtime_CUDAWrapper_cudaCpuDeviceId -1L
#undef CUDAWrapper_runtime_CUDAWrapper_cudaInvalidDeviceId
#define CUDAWrapper_runtime_CUDAWrapper_cudaInvalidDeviceId -2L
    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    setLogLevel
    * Signature: (I)V
    */
    JNIEXPORT void JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_setLogLevel
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetDeviceCountNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetDeviceCountNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaSetDeviceNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaSetDeviceNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaSetDeviceFlagsNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaSetDeviceFlagsNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetDeviceFlagsNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetDeviceFlagsNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaSetValidDevicesNative
    * Signature: ([II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaSetValidDevicesNative
        (JNIEnv *, jclass, jintArray, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetDeviceNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetDeviceNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetDevicePropertiesNative
    * Signature: (LCUDAWrapper/runtime/cudaDeviceProp;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetDevicePropertiesNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceGetAttributeNative
    * Signature: ([III)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceGetAttributeNative
        (JNIEnv *, jclass, jintArray, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceGetP2PAttributeNative
    * Signature: ([IIII)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceGetP2PAttributeNative
        (JNIEnv *, jclass, jintArray, jint, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaChooseDeviceNative
    * Signature: ([ILCUDAWrapper/runtime/cudaDeviceProp;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaChooseDeviceNative
        (JNIEnv *, jclass, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMalloc3DNative
    * Signature: (LCUDAWrapper/runtime/cudaPitchedPtr;LCUDAWrapper/runtime/cudaExtent;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMalloc3DNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMalloc3DArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;LCUDAWrapper/runtime/cudaChannelFormatDesc;LCUDAWrapper/runtime/cudaExtent;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMalloc3DArrayNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMallocMipmappedArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaMipmappedArray;LCUDAWrapper/runtime/cudaChannelFormatDesc;LCUDAWrapper/runtime/cudaExtent;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMallocMipmappedArrayNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetMipmappedArrayLevelNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;LCUDAWrapper/runtime/cudaMipmappedArray;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetMipmappedArrayLevelNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemset3DNative
    * Signature: (LCUDAWrapper/runtime/cudaPitchedPtr;ILCUDAWrapper/runtime/cudaExtent;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemset3DNative
        (JNIEnv *, jclass, jobject, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemsetAsyncNative
    * Signature: (LCUDAWrapper/Pointer;IJLCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemsetAsyncNative
        (JNIEnv *, jclass, jobject, jint, jlong, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemset2DAsyncNative
    * Signature: (LCUDAWrapper/Pointer;JIJJLCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemset2DAsyncNative
        (JNIEnv *, jclass, jobject, jlong, jint, jlong, jlong, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemset3DAsyncNative
    * Signature: (LCUDAWrapper/runtime/cudaPitchedPtr;ILCUDAWrapper/runtime/cudaExtent;LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemset3DAsyncNative
        (JNIEnv *, jclass, jobject, jint, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy3DNative
    * Signature: (LCUDAWrapper/runtime/cudaMemcpy3DParms;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy3DNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy3DPeerNative
    * Signature: (LCUDAWrapper/runtime/cudaMemcpy3DPeerParms;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy3DPeerNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy3DAsyncNative
    * Signature: (LCUDAWrapper/runtime/cudaMemcpy3DParms;LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy3DAsyncNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy3DPeerAsyncNative
    * Signature: (LCUDAWrapper/runtime/cudaMemcpy3DPeerParms;LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy3DPeerAsyncNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemGetInfoNative
    * Signature: ([J[J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemGetInfoNative
        (JNIEnv *, jclass, jlongArray, jlongArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaArrayGetInfoNative
    * Signature: (LCUDAWrapper/runtime/cudaChannelFormatDesc;LCUDAWrapper/runtime/cudaExtent;[ILCUDAWrapper/runtime/cudaArray;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaArrayGetInfoNative
        (JNIEnv *, jclass, jobject, jobject, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaHostAllocNative
    * Signature: (LCUDAWrapper/Pointer;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaHostAllocNative
        (JNIEnv *, jclass, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaHostRegisterNative
    * Signature: (LCUDAWrapper/Pointer;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaHostRegisterNative
        (JNIEnv *, jclass, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaHostUnregisterNative
    * Signature: (LCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaHostUnregisterNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaHostGetDevicePointerNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/Pointer;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaHostGetDevicePointerNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMallocManagedNative
    * Signature: (LCUDAWrapper/Pointer;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMallocManagedNative
        (JNIEnv *, jclass, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMallocNative
    * Signature: (LCUDAWrapper/Pointer;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMallocNative
        (JNIEnv *, jclass, jobject, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMallocHostNative
    * Signature: (LCUDAWrapper/Pointer;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMallocHostNative
        (JNIEnv *, jclass, jobject, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMallocPitchNative
    * Signature: (LCUDAWrapper/Pointer;[JJJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMallocPitchNative
        (JNIEnv *, jclass, jobject, jlongArray, jlong, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMallocArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;LCUDAWrapper/runtime/cudaChannelFormatDesc;JJI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMallocArrayNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaFreeNative
    * Signature: (LCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaFreeNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaFreeHostNative
    * Signature: (LCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaFreeHostNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaFreeArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaFreeArrayNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaFreeMipmappedArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaMipmappedArray;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaFreeMipmappedArrayNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpyNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/Pointer;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpyNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpyPeerNative
    * Signature: (LCUDAWrapper/Pointer;ILCUDAWrapper/Pointer;IJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpyPeerNative
        (JNIEnv *, jclass, jobject, jint, jobject, jint, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpyToArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;JJLCUDAWrapper/Pointer;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpyToArrayNative
        (JNIEnv *, jclass, jobject, jlong, jlong, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpyFromArrayNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/runtime/cudaArray;JJJI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpyFromArrayNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jlong, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpyArrayToArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;JJLCUDAWrapper/runtime/cudaArray;JJJI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpyArrayToArrayNative
        (JNIEnv *, jclass, jobject, jlong, jlong, jobject, jlong, jlong, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy2DNative
    * Signature: (LCUDAWrapper/Pointer;JLCUDAWrapper/Pointer;JJJI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy2DNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jlong, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy2DToArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;JJLCUDAWrapper/Pointer;JJJI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy2DToArrayNative
        (JNIEnv *, jclass, jobject, jlong, jlong, jobject, jlong, jlong, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy2DFromArrayNative
    * Signature: (LCUDAWrapper/Pointer;JLCUDAWrapper/runtime/cudaArray;JJJJI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy2DFromArrayNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jlong, jlong, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy2DArrayToArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;JJLCUDAWrapper/runtime/cudaArray;JJJJI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy2DArrayToArrayNative
        (JNIEnv *, jclass, jobject, jlong, jlong, jobject, jlong, jlong, jlong, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpyAsyncNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/Pointer;JILCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpyAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpyPeerAsyncNative
    * Signature: (LCUDAWrapper/Pointer;ILCUDAWrapper/Pointer;IJLCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpyPeerAsyncNative
        (JNIEnv *, jclass, jobject, jint, jobject, jint, jlong, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpyToArrayAsyncNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;JJLCUDAWrapper/Pointer;JILCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpyToArrayAsyncNative
        (JNIEnv *, jclass, jobject, jlong, jlong, jobject, jlong, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpyFromArrayAsyncNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/runtime/cudaArray;JJJILCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpyFromArrayAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jlong, jlong, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy2DAsyncNative
    * Signature: (LCUDAWrapper/Pointer;JLCUDAWrapper/Pointer;JJJILCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy2DAsyncNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jlong, jlong, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy2DToArrayAsyncNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;JJLCUDAWrapper/Pointer;JJJILCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy2DToArrayAsyncNative
        (JNIEnv *, jclass, jobject, jlong, jlong, jobject, jlong, jlong, jlong, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemcpy2DFromArrayAsyncNative
    * Signature: (LCUDAWrapper/Pointer;JLCUDAWrapper/runtime/cudaArray;JJJJILCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemcpy2DFromArrayAsyncNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jlong, jlong, jlong, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemsetNative
    * Signature: (LCUDAWrapper/Pointer;IJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemsetNative
        (JNIEnv *, jclass, jobject, jint, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemset2DNative
    * Signature: (LCUDAWrapper/Pointer;JIJJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemset2DNative
        (JNIEnv *, jclass, jobject, jlong, jint, jlong, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetChannelDescNative
    * Signature: (LCUDAWrapper/runtime/cudaChannelFormatDesc;LCUDAWrapper/runtime/cudaArray;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetChannelDescNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaCreateChannelDescNative
    * Signature: (IIIII)LCUDAWrapper/runtime/cudaChannelFormatDesc;
    */
    JNIEXPORT jobject JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaCreateChannelDescNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetLastErrorNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetLastErrorNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaPeekAtLastErrorNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaPeekAtLastErrorNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetErrorNameNative
    * Signature: (I)Ljava/lang/String;
    */
    JNIEXPORT jstring JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetErrorNameNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetErrorStringNative
    * Signature: (I)Ljava/lang/String;
    */
    JNIEXPORT jstring JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetErrorStringNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamCreateNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamCreateNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamCreateWithFlagsNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamCreateWithFlagsNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamCreateWithPriorityNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamCreateWithPriorityNative
        (JNIEnv *, jclass, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamGetPriorityNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;[I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamGetPriorityNative
        (JNIEnv *, jclass, jobject, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamGetFlagsNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;[I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamGetFlagsNative
        (JNIEnv *, jclass, jobject, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamDestroyNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamWaitEventNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;LCUDAWrapper/runtime/cudaEvent_t;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamWaitEventNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamAddCallbackNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;LCUDAWrapper/runtime/cudaStreamCallback;Ljava/lang/Object;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamAddCallbackNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamSynchronizeNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamSynchronizeNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamQueryNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamQueryNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaStreamAttachMemAsyncNative
    * Signature: (LCUDAWrapper/runtime/cudaStream_t;LCUDAWrapper/Pointer;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaStreamAttachMemAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaEventCreateNative
    * Signature: (LCUDAWrapper/runtime/cudaEvent_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaEventCreateNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaEventCreateWithFlagsNative
    * Signature: (LCUDAWrapper/runtime/cudaEvent_t;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaEventCreateWithFlagsNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaEventRecordNative
    * Signature: (LCUDAWrapper/runtime/cudaEvent_t;LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaEventRecordNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaEventQueryNative
    * Signature: (LCUDAWrapper/runtime/cudaEvent_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaEventQueryNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaEventSynchronizeNative
    * Signature: (LCUDAWrapper/runtime/cudaEvent_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaEventSynchronizeNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaEventDestroyNative
    * Signature: (LCUDAWrapper/runtime/cudaEvent_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaEventDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaEventElapsedTimeNative
    * Signature: ([FLCUDAWrapper/runtime/cudaEvent_t;LCUDAWrapper/runtime/cudaEvent_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaEventElapsedTimeNative
        (JNIEnv *, jclass, jfloatArray, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceResetNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceResetNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceSynchronizeNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceSynchronizeNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceSetLimitNative
    * Signature: (IJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceSetLimitNative
        (JNIEnv *, jclass, jint, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceGetLimitNative
    * Signature: ([JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceGetLimitNative
        (JNIEnv *, jclass, jlongArray, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceGetCacheConfigNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceGetCacheConfigNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceGetStreamPriorityRangeNative
    * Signature: ([I[I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceGetStreamPriorityRangeNative
        (JNIEnv *, jclass, jintArray, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceGetSharedMemConfigNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceGetSharedMemConfigNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceSetSharedMemConfigNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceSetSharedMemConfigNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceSetCacheConfigNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceSetCacheConfigNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceGetByPCIBusIdNative
    * Signature: ([ILjava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceGetByPCIBusIdNative
        (JNIEnv *, jclass, jintArray, jstring);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceGetPCIBusIdNative
    * Signature: ([Ljava/lang/String;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceGetPCIBusIdNative
        (JNIEnv *, jclass, jobjectArray, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaIpcGetEventHandleNative
    * Signature: (LCUDAWrapper/runtime/cudaIpcEventHandle;LCUDAWrapper/runtime/cudaEvent_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaIpcGetEventHandleNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaIpcOpenEventHandleNative
    * Signature: (LCUDAWrapper/runtime/cudaEvent_t;LCUDAWrapper/runtime/cudaIpcEventHandle;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaIpcOpenEventHandleNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaIpcGetMemHandleNative
    * Signature: (LCUDAWrapper/runtime/cudaIpcMemHandle;LCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaIpcGetMemHandleNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaIpcOpenMemHandleNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/runtime/cudaIpcMemHandle;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaIpcOpenMemHandleNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaIpcCloseMemHandleNative
    * Signature: (LCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaIpcCloseMemHandleNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaThreadExitNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaThreadExitNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaThreadSynchronizeNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaThreadSynchronizeNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaThreadSetLimitNative
    * Signature: (IJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaThreadSetLimitNative
        (JNIEnv *, jclass, jint, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaThreadGetCacheConfigNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaThreadGetCacheConfigNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaThreadSetCacheConfigNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaThreadSetCacheConfigNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaThreadGetLimitNative
    * Signature: ([JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaThreadGetLimitNative
        (JNIEnv *, jclass, jlongArray, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemPrefetchAsyncNative
    * Signature: (LCUDAWrapper/Pointer;JILCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemPrefetchAsyncNative
        (JNIEnv *, jclass, jobject, jlong, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemAdviseNative
    * Signature: (LCUDAWrapper/Pointer;JII)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemAdviseNative
        (JNIEnv *, jclass, jobject, jlong, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemRangeGetAttributeNative
    * Signature: (LCUDAWrapper/Pointer;JILCUDAWrapper/Pointer;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemRangeGetAttributeNative
        (JNIEnv *, jclass, jobject, jlong, jint, jobject, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaMemRangeGetAttributesNative
    * Signature: ([LCUDAWrapper/Pointer;[J[IJLCUDAWrapper/Pointer;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaMemRangeGetAttributesNative
        (JNIEnv *, jclass, jobjectArray, jlongArray, jintArray, jlong, jobject, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaBindTextureNative
    * Signature: ([JLCUDAWrapper/runtime/textureReference;LCUDAWrapper/Pointer;LCUDAWrapper/runtime/cudaChannelFormatDesc;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaBindTextureNative
        (JNIEnv *, jclass, jlongArray, jobject, jobject, jobject, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaBindTexture2DNative
    * Signature: ([JLCUDAWrapper/runtime/textureReference;LCUDAWrapper/Pointer;LCUDAWrapper/runtime/cudaChannelFormatDesc;JJJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaBindTexture2DNative
        (JNIEnv *, jclass, jlongArray, jobject, jobject, jobject, jlong, jlong, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaBindTextureToArrayNative
    * Signature: (LCUDAWrapper/runtime/textureReference;LCUDAWrapper/runtime/cudaArray;LCUDAWrapper/runtime/cudaChannelFormatDesc;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaBindTextureToArrayNative
        (JNIEnv *, jclass, jobject, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaBindTextureToMipmappedArrayNative
    * Signature: (LCUDAWrapper/runtime/textureReference;LCUDAWrapper/runtime/cudaMipmappedArray;LCUDAWrapper/runtime/cudaChannelFormatDesc;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaBindTextureToMipmappedArrayNative
        (JNIEnv *, jclass, jobject, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaUnbindTextureNative
    * Signature: (LCUDAWrapper/runtime/textureReference;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaUnbindTextureNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetTextureAlignmentOffsetNative
    * Signature: ([JLCUDAWrapper/runtime/textureReference;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetTextureAlignmentOffsetNative
        (JNIEnv *, jclass, jlongArray, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaBindSurfaceToArrayNative
    * Signature: (LCUDAWrapper/runtime/surfaceReference;LCUDAWrapper/runtime/cudaArray;LCUDAWrapper/runtime/cudaChannelFormatDesc;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaBindSurfaceToArrayNative
        (JNIEnv *, jclass, jobject, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaCreateTextureObjectNative
    * Signature: (LCUDAWrapper/runtime/cudaTextureObject;LCUDAWrapper/runtime/cudaResourceDesc;LCUDAWrapper/runtime/cudaTextureDesc;LCUDAWrapper/runtime/cudaResourceViewDesc;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaCreateTextureObjectNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDestroyTextureObjectNative
    * Signature: (LCUDAWrapper/runtime/cudaTextureObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDestroyTextureObjectNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetTextureObjectResourceDescNative
    * Signature: (LCUDAWrapper/runtime/cudaResourceDesc;LCUDAWrapper/runtime/cudaTextureObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetTextureObjectResourceDescNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetTextureObjectTextureDescNative
    * Signature: (LCUDAWrapper/runtime/cudaTextureDesc;LCUDAWrapper/runtime/cudaTextureObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetTextureObjectTextureDescNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetTextureObjectResourceViewDescNative
    * Signature: (LCUDAWrapper/runtime/cudaResourceViewDesc;LCUDAWrapper/runtime/cudaTextureObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetTextureObjectResourceViewDescNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaCreateSurfaceObjectNative
    * Signature: (LCUDAWrapper/runtime/cudaSurfaceObject;LCUDAWrapper/runtime/cudaResourceDesc;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaCreateSurfaceObjectNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDestroySurfaceObjectNative
    * Signature: (LCUDAWrapper/runtime/cudaSurfaceObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDestroySurfaceObjectNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGetSurfaceObjectResourceDescNative
    * Signature: (LCUDAWrapper/runtime/cudaResourceDesc;LCUDAWrapper/runtime/cudaSurfaceObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGetSurfaceObjectResourceDescNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaConfigureCallNative
    * Signature: (LCUDAWrapper/runtime/dim3;LCUDAWrapper/runtime/dim3;JLCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaConfigureCallNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaSetupArgumentNative
    * Signature: (LCUDAWrapper/Pointer;JJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaSetupArgumentNative
        (JNIEnv *, jclass, jobject, jlong, jlong);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGLSetGLDeviceNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGLSetGLDeviceNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGLGetDevicesNative
    * Signature: ([I[III)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGLGetDevicesNative
        (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGraphicsGLRegisterImageNative
    * Signature: (LCUDAWrapper/runtime/cudaGraphicsResource;III)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGraphicsGLRegisterImageNative
        (JNIEnv *, jclass, jobject, jint, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGraphicsGLRegisterBufferNative
    * Signature: (LCUDAWrapper/runtime/cudaGraphicsResource;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGraphicsGLRegisterBufferNative
        (JNIEnv *, jclass, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGLMapBufferObjectNative
    * Signature: (LCUDAWrapper/Pointer;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGLMapBufferObjectNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGLUnmapBufferObjectNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGLUnmapBufferObjectNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGLUnregisterBufferObjectNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGLUnregisterBufferObjectNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGLSetBufferObjectMapFlagsNative
    * Signature: (II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGLSetBufferObjectMapFlagsNative
        (JNIEnv *, jclass, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGLMapBufferObjectAsyncNative
    * Signature: (LCUDAWrapper/Pointer;ILCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGLMapBufferObjectAsyncNative
        (JNIEnv *, jclass, jobject, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGLUnmapBufferObjectAsyncNative
    * Signature: (ILCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGLUnmapBufferObjectAsyncNative
        (JNIEnv *, jclass, jint, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDriverGetVersionNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDriverGetVersionNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaRuntimeGetVersionNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaRuntimeGetVersionNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaPointerGetAttributesNative
    * Signature: (LCUDAWrapper/runtime/cudaPointerAttributes;LCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaPointerGetAttributesNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceCanAccessPeerNative
    * Signature: ([III)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceCanAccessPeerNative
        (JNIEnv *, jclass, jintArray, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceEnablePeerAccessNative
    * Signature: (II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceEnablePeerAccessNative
        (JNIEnv *, jclass, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaDeviceDisablePeerAccessNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaDeviceDisablePeerAccessNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGraphicsUnregisterResourceNative
    * Signature: (LCUDAWrapper/runtime/cudaGraphicsResource;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGraphicsUnregisterResourceNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGraphicsResourceSetMapFlagsNative
    * Signature: (LCUDAWrapper/runtime/cudaGraphicsResource;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGraphicsResourceSetMapFlagsNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGraphicsMapResourcesNative
    * Signature: (I[LCUDAWrapper/runtime/cudaGraphicsResource;LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGraphicsMapResourcesNative
        (JNIEnv *, jclass, jint, jobjectArray, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGraphicsUnmapResourcesNative
    * Signature: (I[LCUDAWrapper/runtime/cudaGraphicsResource;LCUDAWrapper/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGraphicsUnmapResourcesNative
        (JNIEnv *, jclass, jint, jobjectArray, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGraphicsResourceGetMappedPointerNative
    * Signature: (LCUDAWrapper/Pointer;[JLCUDAWrapper/runtime/cudaGraphicsResource;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGraphicsResourceGetMappedPointerNative
        (JNIEnv *, jclass, jobject, jlongArray, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGraphicsSubResourceGetMappedArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaArray;LCUDAWrapper/runtime/cudaGraphicsResource;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGraphicsSubResourceGetMappedArrayNative
        (JNIEnv *, jclass, jobject, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaGraphicsResourceGetMappedMipmappedArrayNative
    * Signature: (LCUDAWrapper/runtime/cudaMipmappedArray;LCUDAWrapper/runtime/cudaGraphicsResource;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaGraphicsResourceGetMappedMipmappedArrayNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaProfilerInitializeNative
    * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaProfilerInitializeNative
        (JNIEnv *, jclass, jstring, jstring, jint);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaProfilerStartNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaProfilerStartNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_runtime_CUDAWrapper
    * Method:    cudaProfilerStopNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_runtime_CUDAWrapper_cudaProfilerStopNative
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
