

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CUDAWrapper_driver_CUDAWrapperDriver */

#ifndef _Included_CUDAWrapper_driver_CUDAWrapperDriver
#define _Included_CUDAWrapper_driver_CUDAWrapperDriver
#ifdef __cplusplus
extern "C" {
#endif
#undef CUDAWrapper_driver_CUDAWrapperDriver_CUDA_VERSION
#define CUDAWrapper_driver_CUDAWrapperDriver_CUDA_VERSION 8000L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTALLOC_PORTABLE
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTALLOC_PORTABLE 1L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTALLOC_DEVICEMAP
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTALLOC_DEVICEMAP 2L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTALLOC_WRITECOMBINED
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTALLOC_WRITECOMBINED 4L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTREGISTER_PORTABLE
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTREGISTER_PORTABLE 1L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTREGISTER_DEVICEMAP
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTREGISTER_DEVICEMAP 2L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMPEERREGISTER_DEVICEMAP
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMPEERREGISTER_DEVICEMAP 2L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTREGISTER_IOMEMORY
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_MEMHOSTREGISTER_IOMEMORY 4L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_LAYERED
#define CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_LAYERED 1L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_2DARRAY
#define CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_2DARRAY 1L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_SURFACE_LDST
#define CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_SURFACE_LDST 2L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_CUBEMAP
#define CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_CUBEMAP 4L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_TEXTURE_GATHER
#define CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_TEXTURE_GATHER 8L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_DEPTH_TEXTURE
#define CUDAWrapper_driver_CUDAWrapperDriver_CUDA_ARRAY3D_DEPTH_TEXTURE 16L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_PARAM_TR_DEFAULT
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_PARAM_TR_DEFAULT -1L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_TRSA_OVERRIDE_FORMAT
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_TRSA_OVERRIDE_FORMAT 1L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_TRSF_READ_AS_INTEGER
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_TRSF_READ_AS_INTEGER 1L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_TRSF_NORMALIZED_COORDINATES
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_TRSF_NORMALIZED_COORDINATES 2L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_TRSF_SRGB
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_TRSF_SRGB 16L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_STREAM_CALLBACK_NONBLOCKING
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_STREAM_CALLBACK_NONBLOCKING 0L
#undef CUDAWrapper_driver_CUDAWrapperDriver_CU_STREAM_CALLBACK_BLOCKING
#define CUDAWrapper_driver_CUDAWrapperDriver_CU_STREAM_CALLBACK_BLOCKING 1L
    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    setLogLevel
    * Signature: (I)V
    */
    JNIEXPORT void JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_setLogLevel
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleLoadDataJITNative
    * Signature: (LCUDAWrapper/driver/CUmodule;LCUDAWrapper/Pointer;LCUDAWrapper/driver/JITOptions;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleLoadDataJITNative
        (JNIEnv *, jclass, jobject, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGetErrorStringNative
    * Signature: (I[Ljava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGetErrorStringNative
        (JNIEnv *, jclass, jint, jobjectArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGetErrorNameNative
    * Signature: (I[Ljava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGetErrorNameNative
        (JNIEnv *, jclass, jint, jobjectArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuInitNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuInitNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceGetNative
    * Signature: (LCUDAWrapper/driver/CUdevice;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceGetNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceGetCountNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceGetCountNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceGetNameNative
    * Signature: ([BILCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceGetNameNative
        (JNIEnv *, jclass, jbyteArray, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceComputeCapabilityNative
    * Signature: ([I[ILCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceComputeCapabilityNative
        (JNIEnv *, jclass, jintArray, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDevicePrimaryCtxRetainNative
    * Signature: (LCUDAWrapper/driver/CUcontext;LCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDevicePrimaryCtxRetainNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDevicePrimaryCtxReleaseNative
    * Signature: (LCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDevicePrimaryCtxReleaseNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDevicePrimaryCtxSetFlagsNative
    * Signature: (LCUDAWrapper/driver/CUdevice;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDevicePrimaryCtxSetFlagsNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceTotalMemNative
    * Signature: ([JLCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceTotalMemNative
        (JNIEnv *, jclass, jlongArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceGetPropertiesNative
    * Signature: (LCUDAWrapper/driver/CUdevprop;LCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceGetPropertiesNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceGetAttributeNative
    * Signature: ([IILCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceGetAttributeNative
        (JNIEnv *, jclass, jintArray, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDriverGetVersionNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDriverGetVersionNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxCreateNative
    * Signature: (LCUDAWrapper/driver/CUcontext;ILCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxCreateNative
        (JNIEnv *, jclass, jobject, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxDestroyNative
    * Signature: (LCUDAWrapper/driver/CUcontext;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxAttachNative
    * Signature: (LCUDAWrapper/driver/CUcontext;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxAttachNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxDetachNative
    * Signature: (LCUDAWrapper/driver/CUcontext;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxDetachNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxPushCurrentNative
    * Signature: (LCUDAWrapper/driver/CUcontext;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxPushCurrentNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxPopCurrentNative
    * Signature: (LCUDAWrapper/driver/CUcontext;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxPopCurrentNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxSetCurrentNative
    * Signature: (LCUDAWrapper/driver/CUcontext;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxSetCurrentNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxGetCurrentNative
    * Signature: (LCUDAWrapper/driver/CUcontext;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxGetCurrentNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxGetDeviceNative
    * Signature: (LCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxGetDeviceNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxGetFlagsNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxGetFlagsNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxSynchronizeNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxSynchronizeNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleLoadNative
    * Signature: (LCUDAWrapper/driver/CUmodule;Ljava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleLoadNative
        (JNIEnv *, jclass, jobject, jstring);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleLoadDataNative
    * Signature: (LCUDAWrapper/driver/CUmodule;[B)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleLoadDataNative
        (JNIEnv *, jclass, jobject, jbyteArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleLoadDataExNative
    * Signature: (LCUDAWrapper/driver/CUmodule;LCUDAWrapper/Pointer;I[ILCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleLoadDataExNative
        (JNIEnv *, jclass, jobject, jobject, jint, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleLoadFatBinaryNative
    * Signature: (LCUDAWrapper/driver/CUmodule;[B)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleLoadFatBinaryNative
        (JNIEnv *, jclass, jobject, jbyteArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleUnloadNative
    * Signature: (LCUDAWrapper/driver/CUmodule;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleUnloadNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleGetFunctionNative
    * Signature: (LCUDAWrapper/driver/CUfunction;LCUDAWrapper/driver/CUmodule;Ljava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleGetFunctionNative
        (JNIEnv *, jclass, jobject, jobject, jstring);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleGetGlobalNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;[JLCUDAWrapper/driver/CUmodule;Ljava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleGetGlobalNative
        (JNIEnv *, jclass, jobject, jlongArray, jobject, jstring);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleGetTexRefNative
    * Signature: (LCUDAWrapper/driver/CUtexref;LCUDAWrapper/driver/CUmodule;Ljava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleGetTexRefNative
        (JNIEnv *, jclass, jobject, jobject, jstring);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuModuleGetSurfRefNative
    * Signature: (LCUDAWrapper/driver/CUsurfref;LCUDAWrapper/driver/CUmodule;Ljava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuModuleGetSurfRefNative
        (JNIEnv *, jclass, jobject, jobject, jstring);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuLinkCreateNative
    * Signature: (LCUDAWrapper/driver/JITOptions;LCUDAWrapper/driver/CUlinkState;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuLinkCreateNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuLinkAddDataNative
    * Signature: (LCUDAWrapper/driver/CUlinkState;ILCUDAWrapper/Pointer;JLjava/lang/String;LCUDAWrapper/driver/JITOptions;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuLinkAddDataNative
        (JNIEnv *, jclass, jobject, jint, jobject, jlong, jstring, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuLinkAddFileNative
    * Signature: (LCUDAWrapper/driver/CUlinkState;ILjava/lang/String;LCUDAWrapper/driver/JITOptions;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuLinkAddFileNative
        (JNIEnv *, jclass, jobject, jint, jstring, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuLinkCompleteNative
    * Signature: (LCUDAWrapper/driver/CUlinkState;LCUDAWrapper/Pointer;[J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuLinkCompleteNative
        (JNIEnv *, jclass, jobject, jobject, jlongArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuLinkDestroyNative
    * Signature: (LCUDAWrapper/driver/CUlinkState;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuLinkDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemGetInfoNative
    * Signature: ([J[J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemGetInfoNative
        (JNIEnv *, jclass, jlongArray, jlongArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemHostAllocNative
    * Signature: (LCUDAWrapper/Pointer;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemHostAllocNative
        (JNIEnv *, jclass, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemHostGetDevicePointerNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/Pointer;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemHostGetDevicePointerNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemHostGetFlagsNative
    * Signature: ([ILCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemHostGetFlagsNative
        (JNIEnv *, jclass, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceGetByPCIBusIdNative
    * Signature: (LCUDAWrapper/driver/CUdevice;Ljava/lang/String;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceGetByPCIBusIdNative
        (JNIEnv *, jclass, jobject, jstring);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemAllocManagedNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemAllocManagedNative
        (JNIEnv *, jclass, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceGetPCIBusIdNative
    * Signature: ([Ljava/lang/String;ILCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceGetPCIBusIdNative
        (JNIEnv *, jclass, jobjectArray, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuIpcGetEventHandleNative
    * Signature: (LCUDAWrapper/driver/CUipcEventHandle;LCUDAWrapper/driver/CUevent;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuIpcGetEventHandleNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuIpcOpenEventHandleNative
    * Signature: (LCUDAWrapper/driver/CUevent;LCUDAWrapper/driver/CUipcEventHandle;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuIpcOpenEventHandleNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuIpcGetMemHandleNative
    * Signature: (LCUDAWrapper/driver/CUipcMemHandle;LCUDAWrapper/driver/CUdeviceptr;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuIpcGetMemHandleNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuIpcOpenMemHandleNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUipcMemHandle;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuIpcOpenMemHandleNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuIpcCloseMemHandleNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuIpcCloseMemHandleNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemHostRegisterNative
    * Signature: (LCUDAWrapper/Pointer;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemHostRegisterNative
        (JNIEnv *, jclass, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemHostUnregisterNative
    * Signature: (LCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemHostUnregisterNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUdeviceptr;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyNative
        (JNIEnv *, jclass, jobject, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyPeerNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUcontext;LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUcontext;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyPeerNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemAllocNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemAllocNative
        (JNIEnv *, jclass, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemAllocPitchNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;[JJJI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemAllocPitchNative
        (JNIEnv *, jclass, jobject, jlongArray, jlong, jlong, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemFreeNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemFreeNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemGetAddressRangeNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;[JLCUDAWrapper/driver/CUdeviceptr;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemGetAddressRangeNative
        (JNIEnv *, jclass, jobject, jlongArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemAllocHostNative
    * Signature: (LCUDAWrapper/Pointer;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemAllocHostNative
        (JNIEnv *, jclass, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemFreeHostNative
    * Signature: (LCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemFreeHostNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyHtoDNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/Pointer;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyHtoDNative
        (JNIEnv *, jclass, jobject, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyDtoHNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/driver/CUdeviceptr;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyDtoHNative
        (JNIEnv *, jclass, jobject, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyDtoDNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUdeviceptr;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyDtoDNative
        (JNIEnv *, jclass, jobject, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyDtoANative
    * Signature: (LCUDAWrapper/driver/CUarray;JLCUDAWrapper/driver/CUdeviceptr;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyDtoANative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyAtoDNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUarray;JJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyAtoDNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyHtoANative
    * Signature: (LCUDAWrapper/driver/CUarray;JLCUDAWrapper/Pointer;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyHtoANative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyAtoHNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/driver/CUarray;JJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyAtoHNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyAtoANative
    * Signature: (LCUDAWrapper/driver/CUarray;JLCUDAWrapper/driver/CUarray;JJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyAtoANative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpy2DNative
    * Signature: (LCUDAWrapper/driver/CUDA_MEMCPY2D;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpy2DNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpy2DUnalignedNative
    * Signature: (LCUDAWrapper/driver/CUDA_MEMCPY2D;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpy2DUnalignedNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpy3DNative
    * Signature: (LCUDAWrapper/driver/CUDA_MEMCPY3D;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpy3DNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpy3DPeerNative
    * Signature: (LCUDAWrapper/driver/CUDA_MEMCPY3D_PEER;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpy3DPeerNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyAsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUdeviceptr;JLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyPeerAsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUcontext;LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUcontext;JLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyPeerAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyHtoDAsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/Pointer;JLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyHtoDAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyDtoHAsyncNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/driver/CUdeviceptr;JLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyDtoHAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyDtoDAsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUdeviceptr;JLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyDtoDAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyHtoAAsyncNative
    * Signature: (LCUDAWrapper/driver/CUarray;JLCUDAWrapper/Pointer;JLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyHtoAAsyncNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpyAtoHAsyncNative
    * Signature: (LCUDAWrapper/Pointer;LCUDAWrapper/driver/CUarray;JJLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpyAtoHAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpy2DAsyncNative
    * Signature: (LCUDAWrapper/driver/CUDA_MEMCPY2D;LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpy2DAsyncNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpy3DAsyncNative
    * Signature: (LCUDAWrapper/driver/CUDA_MEMCPY3D;LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpy3DAsyncNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemcpy3DPeerAsyncNative
    * Signature: (LCUDAWrapper/driver/CUDA_MEMCPY3D_PEER;LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemcpy3DPeerAsyncNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD8Native
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;BJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD8Native
        (JNIEnv *, jclass, jobject, jbyte, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD16Native
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;SJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD16Native
        (JNIEnv *, jclass, jobject, jshort, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD32Native
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;IJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD32Native
        (JNIEnv *, jclass, jobject, jint, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD2D8Native
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;JBJJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD2D8Native
        (JNIEnv *, jclass, jobject, jlong, jbyte, jlong, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD2D16Native
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;JSJJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD2D16Native
        (JNIEnv *, jclass, jobject, jlong, jshort, jlong, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD2D32Native
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;JIJJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD2D32Native
        (JNIEnv *, jclass, jobject, jlong, jint, jlong, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD8AsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;BJLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD8AsyncNative
        (JNIEnv *, jclass, jobject, jbyte, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD16AsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;SJLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD16AsyncNative
        (JNIEnv *, jclass, jobject, jshort, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD32AsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;IJLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD32AsyncNative
        (JNIEnv *, jclass, jobject, jint, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD2D8AsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;JBJJLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD2D8AsyncNative
        (JNIEnv *, jclass, jobject, jlong, jbyte, jlong, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD2D16AsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;JSJJLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD2D16AsyncNative
        (JNIEnv *, jclass, jobject, jlong, jshort, jlong, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemsetD2D32AsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;JIJJLCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemsetD2D32AsyncNative
        (JNIEnv *, jclass, jobject, jlong, jint, jlong, jlong, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuFuncGetAttributeNative
    * Signature: ([IILCUDAWrapper/driver/CUfunction;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuFuncGetAttributeNative
        (JNIEnv *, jclass, jintArray, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuFuncSetBlockShapeNative
    * Signature: (LCUDAWrapper/driver/CUfunction;III)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuFuncSetBlockShapeNative
        (JNIEnv *, jclass, jobject, jint, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuFuncSetSharedSizeNative
    * Signature: (LCUDAWrapper/driver/CUfunction;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuFuncSetSharedSizeNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuFuncSetCacheConfigNative
    * Signature: (LCUDAWrapper/driver/CUfunction;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuFuncSetCacheConfigNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuFuncSetSharedMemConfigNative
    * Signature: (LCUDAWrapper/driver/CUfunction;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuFuncSetSharedMemConfigNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuArrayCreateNative
    * Signature: (LCUDAWrapper/driver/CUarray;LCUDAWrapper/driver/CUDA_ARRAY_DESCRIPTOR;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuArrayCreateNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuArrayGetDescriptorNative
    * Signature: (LCUDAWrapper/driver/CUDA_ARRAY_DESCRIPTOR;LCUDAWrapper/driver/CUarray;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuArrayGetDescriptorNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuArrayDestroyNative
    * Signature: (LCUDAWrapper/driver/CUarray;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuArrayDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuArray3DCreateNative
    * Signature: (LCUDAWrapper/driver/CUarray;LCUDAWrapper/driver/CUDA_ARRAY3D_DESCRIPTOR;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuArray3DCreateNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuArray3DGetDescriptorNative
    * Signature: (LCUDAWrapper/driver/CUDA_ARRAY3D_DESCRIPTOR;LCUDAWrapper/driver/CUarray;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuArray3DGetDescriptorNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMipmappedArrayCreateNative
    * Signature: (LCUDAWrapper/driver/CUmipmappedArray;LCUDAWrapper/driver/CUDA_ARRAY3D_DESCRIPTOR;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMipmappedArrayCreateNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMipmappedArrayGetLevelNative
    * Signature: (LCUDAWrapper/driver/CUarray;LCUDAWrapper/driver/CUmipmappedArray;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMipmappedArrayGetLevelNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMipmappedArrayDestroyNative
    * Signature: (LCUDAWrapper/driver/CUmipmappedArray;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMipmappedArrayDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefCreateNative
    * Signature: (LCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefCreateNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefDestroyNative
    * Signature: (LCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetArrayNative
    * Signature: (LCUDAWrapper/driver/CUtexref;LCUDAWrapper/driver/CUarray;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetArrayNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetMipmappedArrayNative
    * Signature: (LCUDAWrapper/driver/CUtexref;LCUDAWrapper/driver/CUmipmappedArray;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetMipmappedArrayNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetAddressNative
    * Signature: ([JLCUDAWrapper/driver/CUtexref;LCUDAWrapper/driver/CUdeviceptr;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetAddressNative
        (JNIEnv *, jclass, jlongArray, jobject, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetFormatNative
    * Signature: (LCUDAWrapper/driver/CUtexref;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetFormatNative
        (JNIEnv *, jclass, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetAddress2DNative
    * Signature: (LCUDAWrapper/driver/CUtexref;LCUDAWrapper/driver/CUDA_ARRAY_DESCRIPTOR;LCUDAWrapper/driver/CUdeviceptr;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetAddress2DNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetAddressModeNative
    * Signature: (LCUDAWrapper/driver/CUtexref;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetAddressModeNative
        (JNIEnv *, jclass, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetFilterModeNative
    * Signature: (LCUDAWrapper/driver/CUtexref;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetFilterModeNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetMipmapFilterModeNative
    * Signature: (LCUDAWrapper/driver/CUtexref;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetMipmapFilterModeNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetMipmapLevelBiasNative
    * Signature: (LCUDAWrapper/driver/CUtexref;F)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetMipmapLevelBiasNative
        (JNIEnv *, jclass, jobject, jfloat);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetMipmapLevelClampNative
    * Signature: (LCUDAWrapper/driver/CUtexref;FF)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetMipmapLevelClampNative
        (JNIEnv *, jclass, jobject, jfloat, jfloat);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetMaxAnisotropyNative
    * Signature: (LCUDAWrapper/driver/CUtexref;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetMaxAnisotropyNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetBorderColorNative
    * Signature: (LCUDAWrapper/driver/CUtexref;[F)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetBorderColorNative
        (JNIEnv *, jclass, jobject, jfloatArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefSetFlagsNative
    * Signature: (LCUDAWrapper/driver/CUtexref;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefSetFlagsNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetAddressNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;LCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetAddressNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetArrayNative
    * Signature: (LCUDAWrapper/driver/CUarray;LCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetArrayNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetMipmappedArrayNative
    * Signature: (LCUDAWrapper/driver/CUmipmappedArray;LCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetMipmappedArrayNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetAddressModeNative
    * Signature: ([ILCUDAWrapper/driver/CUtexref;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetAddressModeNative
        (JNIEnv *, jclass, jintArray, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetFilterModeNative
    * Signature: ([ILCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetFilterModeNative
        (JNIEnv *, jclass, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetFormatNative
    * Signature: ([I[ILCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetFormatNative
        (JNIEnv *, jclass, jintArray, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetMipmapFilterModeNative
    * Signature: ([ILCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetMipmapFilterModeNative
        (JNIEnv *, jclass, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetMipmapLevelBiasNative
    * Signature: ([FLCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetMipmapLevelBiasNative
        (JNIEnv *, jclass, jfloatArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetMipmapLevelClampNative
    * Signature: ([F[FLCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetMipmapLevelClampNative
        (JNIEnv *, jclass, jfloatArray, jfloatArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetMaxAnisotropyNative
    * Signature: ([ILCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetMaxAnisotropyNative
        (JNIEnv *, jclass, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetBorderColorNative
    * Signature: ([FLCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetBorderColorNative
        (JNIEnv *, jclass, jfloatArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexRefGetFlagsNative
    * Signature: ([ILCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexRefGetFlagsNative
        (JNIEnv *, jclass, jintArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuSurfRefSetArrayNative
    * Signature: (LCUDAWrapper/driver/CUsurfref;LCUDAWrapper/driver/CUarray;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuSurfRefSetArrayNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuSurfRefGetArrayNative
    * Signature: (LCUDAWrapper/driver/CUarray;LCUDAWrapper/driver/CUsurfref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuSurfRefGetArrayNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexObjectCreateNative
    * Signature: (LCUDAWrapper/driver/CUtexObject;LCUDAWrapper/driver/CUDA_RESOURCE_DESC;LCUDAWrapper/driver/CUDA_TEXTURE_DESC;LCUDAWrapper/driver/CUDA_RESOURCE_VIEW_DESC;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexObjectCreateNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexObjectDestroyNative
    * Signature: (LCUDAWrapper/driver/CUtexObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexObjectDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexObjectGetResourceDescNative
    * Signature: (LCUDAWrapper/driver/CUDA_RESOURCE_DESC;LCUDAWrapper/driver/CUtexObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexObjectGetResourceDescNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexObjectGetTextureDescNative
    * Signature: (LCUDAWrapper/driver/CUDA_TEXTURE_DESC;LCUDAWrapper/driver/CUtexObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexObjectGetTextureDescNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuTexObjectGetResourceViewDescNative
    * Signature: (LCUDAWrapper/driver/CUDA_RESOURCE_VIEW_DESC;LCUDAWrapper/driver/CUtexObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuTexObjectGetResourceViewDescNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuSurfObjectCreateNative
    * Signature: (LCUDAWrapper/driver/CUsurfObject;LCUDAWrapper/driver/CUDA_RESOURCE_DESC;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuSurfObjectCreateNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuSurfObjectDestroyNative
    * Signature: (LCUDAWrapper/driver/CUsurfObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuSurfObjectDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuSurfObjectGetResourceDescNative
    * Signature: (LCUDAWrapper/driver/CUDA_RESOURCE_DESC;LCUDAWrapper/driver/CUsurfObject;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuSurfObjectGetResourceDescNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceCanAccessPeerNative
    * Signature: ([ILCUDAWrapper/driver/CUdevice;LCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceCanAccessPeerNative
        (JNIEnv *, jclass, jintArray, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuDeviceGetP2PAttributeNative
    * Signature: ([IILCUDAWrapper/driver/CUdevice;LCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuDeviceGetP2PAttributeNative
        (JNIEnv *, jclass, jintArray, jint, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxEnablePeerAccessNative
    * Signature: (LCUDAWrapper/driver/CUcontext;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxEnablePeerAccessNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxDisablePeerAccessNative
    * Signature: (LCUDAWrapper/driver/CUcontext;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxDisablePeerAccessNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuParamSetSizeNative
    * Signature: (LCUDAWrapper/driver/CUfunction;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuParamSetSizeNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuParamSetiNative
    * Signature: (LCUDAWrapper/driver/CUfunction;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuParamSetiNative
        (JNIEnv *, jclass, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuParamSetfNative
    * Signature: (LCUDAWrapper/driver/CUfunction;IF)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuParamSetfNative
        (JNIEnv *, jclass, jobject, jint, jfloat);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuParamSetvNative
    * Signature: (LCUDAWrapper/driver/CUfunction;ILCUDAWrapper/Pointer;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuParamSetvNative
        (JNIEnv *, jclass, jobject, jint, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuParamSetTexRefNative
    * Signature: (LCUDAWrapper/driver/CUfunction;ILCUDAWrapper/driver/CUtexref;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuParamSetTexRefNative
        (JNIEnv *, jclass, jobject, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuOccupancyMaxActiveBlocksPerMultiprocessorNative
    * Signature: ([ILCUDAWrapper/driver/CUfunction;IJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuOccupancyMaxActiveBlocksPerMultiprocessorNative
        (JNIEnv *, jclass, jintArray, jobject, jint, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlagsNative
    * Signature: ([ILCUDAWrapper/driver/CUfunction;IJI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlagsNative
        (JNIEnv *, jclass, jintArray, jobject, jint, jlong, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuOccupancyMaxPotentialBlockSizeNative
    * Signature: ([I[ILCUDAWrapper/driver/CUfunction;LCUDAWrapper/driver/CUoccupancyB2DSize;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuOccupancyMaxPotentialBlockSizeNative
        (JNIEnv *, jclass, jintArray, jintArray, jobject, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuOccupancyMaxPotentialBlockSizeWithFlagsNative
    * Signature: ([I[ILCUDAWrapper/driver/CUfunction;LCUDAWrapper/driver/CUoccupancyB2DSize;JII)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuOccupancyMaxPotentialBlockSizeWithFlagsNative
        (JNIEnv *, jclass, jintArray, jintArray, jobject, jobject, jlong, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuLaunchNative
    * Signature: (LCUDAWrapper/driver/CUfunction;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuLaunchNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuLaunchGridNative
    * Signature: (LCUDAWrapper/driver/CUfunction;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuLaunchGridNative
        (JNIEnv *, jclass, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuLaunchGridAsyncNative
    * Signature: (LCUDAWrapper/driver/CUfunction;IILCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuLaunchGridAsyncNative
        (JNIEnv *, jclass, jobject, jint, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuEventCreateNative
    * Signature: (LCUDAWrapper/driver/CUevent;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuEventCreateNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuEventRecordNative
    * Signature: (LCUDAWrapper/driver/CUevent;LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuEventRecordNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuEventQueryNative
    * Signature: (LCUDAWrapper/driver/CUevent;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuEventQueryNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuEventSynchronizeNative
    * Signature: (LCUDAWrapper/driver/CUevent;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuEventSynchronizeNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuEventDestroyNative
    * Signature: (LCUDAWrapper/driver/CUevent;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuEventDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuEventElapsedTimeNative
    * Signature: ([FLCUDAWrapper/driver/CUevent;LCUDAWrapper/driver/CUevent;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuEventElapsedTimeNative
        (JNIEnv *, jclass, jfloatArray, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamWaitValue32Native
    * Signature: (LCUDAWrapper/driver/CUstream;LCUDAWrapper/driver/CUdeviceptr;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamWaitValue32Native
        (JNIEnv *, jclass, jobject, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamWriteValue32Native
    * Signature: (LCUDAWrapper/driver/CUstream;LCUDAWrapper/driver/CUdeviceptr;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamWriteValue32Native
        (JNIEnv *, jclass, jobject, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuPointerGetAttributeNative
    * Signature: (LCUDAWrapper/Pointer;ILCUDAWrapper/driver/CUdeviceptr;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuPointerGetAttributeNative
        (JNIEnv *, jclass, jobject, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemPrefetchAsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;JLCUDAWrapper/driver/CUdevice;LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemPrefetchAsyncNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemAdviseNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;JILCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemAdviseNative
        (JNIEnv *, jclass, jobject, jlong, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemRangeGetAttributeNative
    * Signature: (LCUDAWrapper/Pointer;JILCUDAWrapper/driver/CUdeviceptr;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemRangeGetAttributeNative
        (JNIEnv *, jclass, jobject, jlong, jint, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuMemRangeGetAttributesNative
    * Signature: ([LCUDAWrapper/Pointer;[J[IJLCUDAWrapper/driver/CUdeviceptr;J)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuMemRangeGetAttributesNative
        (JNIEnv *, jclass, jobjectArray, jlongArray, jintArray, jlong, jobject, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuPointerSetAttributeNative
    * Signature: (LCUDAWrapper/Pointer;ILCUDAWrapper/driver/CUdeviceptr;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuPointerSetAttributeNative
        (JNIEnv *, jclass, jobject, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuPointerGetAttributesNative
    * Signature: (I[ILCUDAWrapper/Pointer;LCUDAWrapper/driver/CUdeviceptr;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuPointerGetAttributesNative
        (JNIEnv *, jclass, jint, jintArray, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamCreateNative
    * Signature: (LCUDAWrapper/driver/CUstream;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamCreateNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamCreateWithPriorityNative
    * Signature: (LCUDAWrapper/driver/CUstream;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamCreateWithPriorityNative
        (JNIEnv *, jclass, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamGetPriorityNative
    * Signature: (LCUDAWrapper/driver/CUstream;[I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamGetPriorityNative
        (JNIEnv *, jclass, jobject, jintArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamGetFlagsNative
    * Signature: (LCUDAWrapper/driver/CUstream;[I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamGetFlagsNative
        (JNIEnv *, jclass, jobject, jintArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamWaitEventNative
    * Signature: (LCUDAWrapper/driver/CUstream;LCUDAWrapper/driver/CUevent;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamWaitEventNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamAddCallbackNative
    * Signature: (LCUDAWrapper/driver/CUstream;LCUDAWrapper/driver/CUstreamCallback;Ljava/lang/Object;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamAddCallbackNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamAttachMemAsyncNative
    * Signature: (LCUDAWrapper/driver/CUstream;LCUDAWrapper/driver/CUdeviceptr;JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamAttachMemAsyncNative
        (JNIEnv *, jclass, jobject, jobject, jlong, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamQueryNative
    * Signature: (LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamQueryNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamSynchronizeNative
    * Signature: (LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamSynchronizeNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuStreamDestroyNative
    * Signature: (LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuStreamDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGLInitNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGLInitNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGLCtxCreateNative
    * Signature: (LCUDAWrapper/driver/CUcontext;ILCUDAWrapper/driver/CUdevice;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGLCtxCreateNative
        (JNIEnv *, jclass, jobject, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGLGetDevicesNative
    * Signature: ([I[LCUDAWrapper/driver/CUdevice;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGLGetDevicesNative
        (JNIEnv *, jclass, jintArray, jobjectArray, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGraphicsGLRegisterBufferNative
    * Signature: (LCUDAWrapper/driver/CUgraphicsResource;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGraphicsGLRegisterBufferNative
        (JNIEnv *, jclass, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGraphicsGLRegisterImageNative
    * Signature: (LCUDAWrapper/driver/CUgraphicsResource;III)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGraphicsGLRegisterImageNative
        (JNIEnv *, jclass, jobject, jint, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGLMapBufferObjectNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;[JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGLMapBufferObjectNative
        (JNIEnv *, jclass, jobject, jlongArray, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGLUnmapBufferObjectNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGLUnmapBufferObjectNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGLUnregisterBufferObjectNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGLUnregisterBufferObjectNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGLSetBufferObjectMapFlagsNative
    * Signature: (II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGLSetBufferObjectMapFlagsNative
        (JNIEnv *, jclass, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGLMapBufferObjectAsyncNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;[JILCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGLMapBufferObjectAsyncNative
        (JNIEnv *, jclass, jobject, jlongArray, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGLUnmapBufferObjectAsyncNative
    * Signature: (ILCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGLUnmapBufferObjectAsyncNative
        (JNIEnv *, jclass, jint, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGraphicsUnregisterResourceNative
    * Signature: (LCUDAWrapper/driver/CUgraphicsResource;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGraphicsUnregisterResourceNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGraphicsSubResourceGetMappedArrayNative
    * Signature: (LCUDAWrapper/driver/CUarray;LCUDAWrapper/driver/CUgraphicsResource;II)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGraphicsSubResourceGetMappedArrayNative
        (JNIEnv *, jclass, jobject, jobject, jint, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGraphicsResourceGetMappedMipmappedArrayNative
    * Signature: (LCUDAWrapper/driver/CUmipmappedArray;LCUDAWrapper/driver/CUgraphicsResource;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGraphicsResourceGetMappedMipmappedArrayNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGraphicsResourceGetMappedPointerNative
    * Signature: (LCUDAWrapper/driver/CUdeviceptr;[JLCUDAWrapper/driver/CUgraphicsResource;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGraphicsResourceGetMappedPointerNative
        (JNIEnv *, jclass, jobject, jlongArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGraphicsResourceSetMapFlagsNative
    * Signature: (LCUDAWrapper/driver/CUgraphicsResource;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGraphicsResourceSetMapFlagsNative
        (JNIEnv *, jclass, jobject, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGraphicsMapResourcesNative
    * Signature: (I[LCUDAWrapper/driver/CUgraphicsResource;LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGraphicsMapResourcesNative
        (JNIEnv *, jclass, jint, jobjectArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuGraphicsUnmapResourcesNative
    * Signature: (I[LCUDAWrapper/driver/CUgraphicsResource;LCUDAWrapper/driver/CUstream;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuGraphicsUnmapResourcesNative
        (JNIEnv *, jclass, jint, jobjectArray, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxSetLimitNative
    * Signature: (IJ)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxSetLimitNative
        (JNIEnv *, jclass, jint, jlong);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxGetCacheConfigNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxGetCacheConfigNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxSetCacheConfigNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxSetCacheConfigNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxGetSharedMemConfigNative
    * Signature: ([I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxGetSharedMemConfigNative
        (JNIEnv *, jclass, jintArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxSetSharedMemConfigNative
    * Signature: (I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxSetSharedMemConfigNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxGetApiVersionNative
    * Signature: (LCUDAWrapper/driver/CUcontext;[I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxGetApiVersionNative
        (JNIEnv *, jclass, jobject, jintArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxGetStreamPriorityRangeNative
    * Signature: ([I[I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxGetStreamPriorityRangeNative
        (JNIEnv *, jclass, jintArray, jintArray);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuLaunchKernelNative
    * Signature: (LCUDAWrapper/driver/CUfunction;IIIIIIILCUDAWrapper/driver/CUstream;LCUDAWrapper/Pointer;LCUDAWrapper/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuLaunchKernelNative
        (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint, jobject, jobject, jobject);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuCtxGetLimitNative
    * Signature: ([JI)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuCtxGetLimitNative
        (JNIEnv *, jclass, jlongArray, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuProfilerInitializeNative
    * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuProfilerInitializeNative
        (JNIEnv *, jclass, jstring, jstring, jint);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuProfilerStartNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuProfilerStartNative
        (JNIEnv *, jclass);

    /*
    * Class:     CUDAWrapper_driver_CUDAWrapperDriver
    * Method:    cuProfilerStopNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_CUDAWrapper_driver_CUDAWrapperDriver_cuProfilerStopNative
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
